### ISSUE TITLE
feat: Database Client

### ISSUE THREAD

**Issue by JcbSm** [JcbSm/Bridge#1]
Preferably stored as simply as:

| Field | Datatype | Constraints | Options... |
|-|-|-|-|
| `user_id` | VARCHAR/BIGINT | PK | NOT NULL |
| `username` | VARCHAR |
| `uuid` | VARCHAR | 

`user_id` being the Discord user ID.
`username` will just be the last username they issued the command with, which would be inconsisten if the user changes their MC username.
`uuid` however would be persistent.

[Implement the logic here](https://github.com/JcbSm/Bridge/blob/03cea84b90807b7645edf974ab3a92035bb34878/src/main/java/github/jcbsm/bridge/discord/commands/WhitelistCommand.java#L59)

**Comment by JcbSm** [comment]
Implement the DatabaseClient at `src/main/java/github/jcbsm/bridge/database`.

Any files storing information should be stored in the plugin's data foler (Accessed using `org.bukkit.plugin.java.JavaPlugin.getDataFolder()`)

**Comment by JcbSm** [comment]
Minecraft username. 

Any kind of db works really. Its not going to be very large. Just needs to be local

**Comment by sanamorii** [comment]
Hi, like @JcbSm the database is probably not going to be extremely large. If you would like to get start then I was originally going to use SQLite as the db but that might be changed to mysql.

**Comment by JcbSm** [comment]
Implemented :D
