### ISSUE TITLE
feat: nicer logo

### ISSUE THREAD

**Issue by JcbSm** [JcbSm/Bridge#11]
Qiang pls

**Comment by sanamorii** [comment]
Ok
![F3469F63-A25A-49ED-A52B-79CE0F5E8D06-1.jpg](https://github.com/JcbSm/Bridge/assets/86570135/b2980257-e600-4912-8e1f-1abe6ad0af6d)

**Comment by JcbSm** [comment]
Make a PR from Dev and just replace /assets/logo.png thx
